### ISSUE TITLE
several errors on install

### ISSUE THREAD

**Issue by avidteacher** [marsvaardig/osc-node#1]
The install.sh throws several errors while installing, and then (obviously) won't run properly.

Here's where the errors seem to start:

> serialport@4.0.7 install /home/pi/osc-node/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/opt/nodejs/bin/node',
node-pre-gyp verb cli   '/home/pi/osc-node/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@11.11.0 | linux | arm
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/pi/osc-node/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v67-linux-arm.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v67-linux-arm.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v67-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@11.11.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v67-linux-arm.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v67-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@11.11.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]

I'm trying to install on a pi zero - could that be the problem?  

Edit 3/19/19 - picked up a pi 3b+ and it works fine there.   Would still like to be able to run it on a zero if possible - great footprint to put in props!

**Comment by tomjanssens** [comment]
I just did a fresh installation on a new Pi 4 without any issues. I guess the Pi Zero will be the problem.
